create table accounts
(
    account_id integer generated by default as identity
        constraint accounts_pkey
            primary key,
    password varchar(255),
    email varchar(255)
        constraint uk_n7ihswpy07ci568w34q0oi8he
            unique,
    role varchar(255)
);

create table postal_codes
(
    postal_id integer generated by default as identity
        constraint postal_codes_pkey
            primary key,
    city varchar(255),
    postal_code varchar(255)
        constraint uk_g2hm78ki5kcxnvsctbkyqcfs6
            unique
);

create table addresses
(
    address_id integer generated by default as identity
        constraint addresses_pkey
            primary key,
    street_name varchar(255),
    street_number varchar(255),
    postal_id integer not null
        constraint fk4w4cpvp4hh9dshtn6w2auyuv
            references postal_codes
);

create table contact_persons
(
    contact_person_id integer generated by default as identity
        constraint contact_persons_pkey
            primary key,
    email varchar(255)
        constraint uk_q539x2dqaauhk1g2vd9xqj57d
            unique,
    full_name varchar(255),
    mobile_phone_number varchar(255),
    telephone_number varchar(255),
    address_id integer
        constraint fkmjh1g4jvkgf6xtqlrwyhn52rv
            references addresses
);

create table parking_lot
(
    parking_id integer generated by default as identity
        constraint parking_lot_pkey
            primary key,
    category varchar(255),
    max_capacity integer,
    parking_lot_name varchar(255),
    currency integer,
    value double precision,
    address_id integer
        constraint fkn4wtrjuurhn0s1tg7olkpct9x
            references addresses,
    contact_person_id integer
        constraint fkifasg5wl68gyu8etfkeijkegs
            references contact_persons
);

