create table parking_spots
(
    parking_spot_id            integer generated by default as identity
        constraint parking_spots_pkey
            primary key,
    member_id    integer
        constraint fk_parking_spots_to_members references members,
    parking_lot_id integer
        constraint fk_parking_spots_to_parking_lot references parking_lot,
    plate_number varchar(255),
    issuing_country varchar(255),
    start_allocation_date date
);
