create table divisions (
    division_id integer generated by default as identity
        constraint divisions_pkey
            primary key,
    name varchar(255),
    original_name varchar(255),
    director varchar(255)
);

alter table divisions owner to student;
